# Site settings
title: Sajjad Ayoubi
email: sadeveloper360@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: ayoubi_sajjad
github_username: sajjjadayobi
linkedin_username: sed-amin-taheri
telegram_username: Sajjadayobi

# Build settings
markdown: GFM
